// <auto-generated />
using System;
using BizimMarket.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BizimMarket.Migrations
{
    [DbContext(typeof(BizimMarketContext))]
    partial class BizimMarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BizimMarket.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Atıştırmalık"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Dondurma"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Fırın"
                        });
                });

            modelBuilder.Entity("BizimMarket.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ProductImage = "kinderjoy.jpg",
                            ProductName = "Kinder Joy 20g",
                            ProductPrice = 7.90m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ProductImage = "toblerone.jpg",
                            ProductName = "Toblerone Sütlü Çikolata 100g",
                            ProductPrice = 18.90m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ProductImage = "tadelle.jpg",
                            ProductName = "Tadelle Fındık Dolgulu Sütlü Çikolata 30g",
                            ProductPrice = 4.95m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ProductImage = "algidamaras.jpg",
                            ProductName = "Algida Maraş Usulü Sade Çikolata Dondurma 500ml",
                            ProductPrice = 28.50m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ProductImage = "cartedormeyve.jpg",
                            ProductName = "Carte d'Or Selection Meyve Şöleni 850ml",
                            ProductPrice = 36.90m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            ProductImage = "miniksandvic.jpg",
                            ProductName = "Minik Sandviç 10'lu",
                            ProductPrice = 17.90m
                        });
                });

            modelBuilder.Entity("BizimMarket.Models.Product", b =>
                {
                    b.HasOne("BizimMarket.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BizimMarket.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
